sudo: false
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2018.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core
  - mv ../ai-zend2-i18n ext/
  - composer require "zendframework/zend-servicemanager" "2.3.*"
  - composer require "zendframework/zend-i18n" "2.3.*"
  - composer install

script: vendor/bin/phing -Ddir=ext/ai-zend2-i18n coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-zend2-i18n/.coveralls.yml
