language: php
php:
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=2015.03 git://github.com/nsendetzky/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-zend2-i18n ext/
  - composer require "zendframework/zend-servicemanager" "2.3.*"
  - composer require "zendframework/zend-i18n" "2.3.*"
  - composer install
script: "vendor/bin/phing -Ddir=ext/ai-zend2-i18n testext && vendor/bin/phing -Ddir=ext/ai-zend2-i18n checkext"
